apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'com.styro.launcher'
version = '1.0.0'

android {
  compileSdkVersion 36
  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36
  }
}

dependencies {
  implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
}
